#!/bin/bash

# --------------------------------------
# | Created By Bruno Santos (LazyDogg) |
# |  07/02/2025 - 02:37 (GMT -03:00)   |
# --------------------------------------


if [[ $(whoami) != "root" ]]; then
	dialog --clear --title "Cancelando" --msgbox "Você precisa estar como ROOT\n(Você digitou sudo?)" 130 160
	exit 1
fi



function cancel(){
	if [[ $1 == "" ]]; then
		dialog --title "Cancelando" --msgbox "Abortando o Processo..." 130 160
		exit 1
	fi
}


disk=($(dialog \
	--title "Seleção de Disco" \
	--yes-label "Selecionar" \
	--no-label "Cancelar" \
	--stdout \
	--menu \
	"Por favor selecione o disco a ser limpo e formatado:" \
	150 \
	210 \
	200 \
 	$(lsblk --output PATH -d -n | sed 's/\(^\/dev\/[^>]*\)/\1\ <--/')))

cancel $disk

options_part=($(dialog \
	--title "Sistema de Partição" \
	--yes-label "Selecionar" \
	--no-label "Cancelar" \
	--stdout \
	--menu \
	"Sistema de Partição" \
	180 \
	100 \
	80 \
	"MBR" "" \
	"GPT" "" ))

cancel $options_part

options_fs=($(dialog \
	--title "Sistema de Arquivos" \
	--yes-label "Selecionar" \
	--stdout \
	--no-label "Cancelar" \
	--menu \
	"Sistema de Arquivos" \
	210 \
	100 \
	80 \
	"NTFS" "" \
	"EXT4" "" \
	"FAT32" "" \
	"exFAT" "" ))
	
cancel $options_fs

sure=($(dialog --stdout --ok-label "Confirma" --cancel-label "Cancela" --msgbox \
	"Aqui se encontra um resumo de suas escolhas:\nDisco: $disk\nSistema de Partição: $options_part\nSistema de Arquivos: $options_fs" \
	100 150 && echo "ok" ))
cancel $sure

warning=($(dialog --stdout \
	--title "Atenção!" \
	--yes-label "OK" \
	--no-label "CANCELAR" \
	--yesno \
	"Atenção! \n Qualquer dado no disco será apagado e não será recuperável \n TEM CERTEZA?" \
	100 150 && echo "ok"))

cancel $warning

wipefs -a $disk &>> /dev/null
if [[ $? == 0 ]]; then
	if [[ $options_part == "MBR" ]]; then
		echo -e "label: dos" |	sfdisk -q $disk
		if [[ $? == 0 ]]; then
			echo -e "," | sfdisk -q $disk
		fi
		if [[ $? == 0 ]]; then
			if [[ $options_fs == "NTFS" || $options_fs == "exFAT" ]]; then
				echo -e "type=07" | sfdisk -N 1 -q $disk &>> /dev/null
				if [[ $? == 0 ]]; then
					if [[ $options_fs == "NTFS" ]]; then
						mkfs.ntfs -f $(lsblk $disk -n -p -o PATH | tail -n 1) &>> /dev/null
						exit 0
					fi
					if [[ $options_fs == "exFAT" ]]; then
						mkfs.exfat $(lsblk $disk -n -p -o PATH | tail -n 1) &>> /dev/null
						exit 0
					fi 
				fi 
			fi
			if [[ $options_fs == "FAT32" ]]; then
				echo -e "type=0b" | sfdisk -N 1 -q $disk
				if [[ $? == 0 ]]; then
					mkfs.vfat -F 32 $(lsblk $disk -n -p -o PATH | tail -n 1) &>> /dev/null
					exit 0
				fi
			fi
			if [[ $options_fs == "EXT4" ]]; then
				mkfs.ext4 $(lsblk $disk -n -p -o PATH | tail -n 1) &>> /dev/null
				exit 0
			fi
		fi
	fi

	if [[ $options_part == "GPT" ]]; then
		echo -e "label: gpt" |	sfdisk -q $disk
		if [[ $? == 0 ]]; then
			echo -e "," | sfdisk -q $disk
		fi
		if [[ $? == 0 ]]; then
			if [[ $options_fs != "EXT4" ]]; then
				echo -e "type=EBD0A0A2-B9E5-4433-87C0-68B6B72699C7" | sfdisk -N 1 -q $disk
				if [[ $? == 0 ]]; then
					if [[ $options_fs == "NTFS" ]]; then
						mkfs.ntfs -f $(lsblk $disk -n -p -o PATH | tail -n 1) &>> /dev/null
						exit 0
					fi
					if [[ $options_fs == "exFAT" ]]; then
						mkfs.exfat $(lsblk $disk -n -p -o PATH | tail -n 1) &>> /dev/null
						exit 0
					fi
					if [[ $options_fs == "FAT32" ]]; then
						mkfs.vfat -F 32 $(lsblk $disk -n -p -o PATH | tail -n 1) &>> /dev/null
						exit 0
					fi
				fi
			
			else
				echo -e "type=0FC63DAF-8483-4772-8E79-3D69D8477DE4" | sfdisk -N 1 -q $disk
				if [[ $? == 0 ]]; then
					mkfs.ext4 $(lsblk $disk -n -p -o PATH | tail -n 1) &>> /dev/null
					exit 0
				fi
			fi
		fi
	fi
fi


dialog  --title "Cancelando" --msgbox  "Erro: Não foi Possível Formatar o Disco...\nAbortando..." 80 130
exit 1

